# Configuration for filenames before running simulations.
# --------------------------------------------------------
# Left-side name = Key used by the code; Right-side name = User-defined filename
# All filenames are compulsory to run the MEGARA DRP, except for 2_ModelMap, 5_TwilightFlat, 
# 8_LcbImage_diffuse_light and healing.
# If VPH is LR-U, master_traces_LRU_20220325_healed(.json) file is compulsory.

VPH: LR-R

0_Bias: 0_bias
1_TraceMap: 1_tracemap
2_ModelMap:
3_WaveCalib: 3_wavecalib
3_WaveCalib_check: 3_WaveCalib_check
4_FiberFlat: 4_fiberflat
5_TwilightFlat:
6_LcbAdquisition: 6_Lcbadquisition
7_StandardStar: 7_Standardstar
8_LcbImage: 8_reduce_LCB
8_LcbImage_diffuse_light:

healing: healing
master_traces_LRU_20220325_healed: